-- =====================================================================
-- PROJECT GOLDEN CHILD — v2.3.2 STORAGE PERMISSIONS FIX
--
-- Safe to run repeatedly.
-- This fixes the exact permission path used to CREATE signed upload URLs.
-- It does not delete existing images or event records.
-- =====================================================================

-- 1. Ensure the bucket exists and has the correct limits.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'event-public',
  'event-public',
  true,
  15728640,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  name=excluded.name,
  public=excluded.public,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

-- 2. Explicitly grant the backend service role the Storage permissions
-- required by signed-upload creation and post-upload verification.
--
-- Supabase secret keys run as service_role. RLS is bypassed for that role,
-- but PostgreSQL table grants are still checked first.
grant usage on schema storage to service_role;

grant select
on table storage.buckets
to service_role;

grant select, insert, update, delete
on table storage.objects
to service_role;

-- Keep postgres owner access explicit as well.
grant all
on table storage.buckets
to postgres;

grant all
on table storage.objects
to postgres;

-- 3. Keep public file delivery enabled. Uploading still requires the
-- short-lived signed token generated by the authenticated PGC admin server.
update storage.buckets
set public=true,
    file_size_limit=15728640,
    allowed_mime_types=array['image/jpeg','image/png','image/webp']
where id='event-public';

-- 4. Update application schema marker.
insert into public.pgc_schema_meta(version,applied_at)
values ('2.3.2',clock_timestamp())
on conflict (version) do update
set applied_at=excluded.applied_at;

notify pgrst, 'reload schema';

-- =====================================================================
-- FINAL DATABASE CHECK
--
-- Expected:
-- bucket_exists = true
-- public = true
-- file_size_limit = 15728640
-- service_role_can_read_bucket = true
-- service_role_can_insert_objects = true
-- service_role_can_select_objects = true
-- =====================================================================

select
  exists(
    select 1
    from storage.buckets
    where id='event-public'
  ) as bucket_exists,

  (
    select public
    from storage.buckets
    where id='event-public'
  ) as public,

  (
    select file_size_limit
    from storage.buckets
    where id='event-public'
  ) as file_size_limit,

  has_table_privilege(
    'service_role',
    'storage.buckets',
    'SELECT'
  ) as service_role_can_read_bucket,

  has_table_privilege(
    'service_role',
    'storage.objects',
    'INSERT'
  ) as service_role_can_insert_objects,

  has_table_privilege(
    'service_role',
    'storage.objects',
    'SELECT'
  ) as service_role_can_select_objects;
