-- =====================================================================
-- PROJECT GOLDEN CHILD — v2.6.0 UPDATE
-- Selected-recipient communications + poster attachments
--
-- Safe to run repeatedly. Existing data is retained.
-- =====================================================================

alter table public.pgc_communications add column if not exists attachment_name text;
alter table public.pgc_communications add column if not exists attachment_path text;
alter table public.pgc_communications add column if not exists attachment_mime_type text;
alter table public.pgc_communications add column if not exists attachment_size bigint;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'communication-attachments',
  'communication-attachments',
  false,
  10485760,
  array['image/jpeg','image/png','image/webp','application/pdf']
)
on conflict (id) do update set
  name=excluded.name,
  public=excluded.public,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

-- Upload/download URLs are generated by the authenticated server using the
-- Supabase server key. No public storage.objects policies are required.

insert into public.pgc_schema_meta(version,applied_at)
values ('2.6.0',clock_timestamp())
on conflict (version) do update
set applied_at=excluded.applied_at;

notify pgrst, 'reload schema';

-- FINAL CHECK A — expected result: ZERO ROWS.
with required(table_name,column_name) as (
  values
    ('pgc_communications','attachment_name'),
    ('pgc_communications','attachment_path'),
    ('pgc_communications','attachment_mime_type'),
    ('pgc_communications','attachment_size')
)
select required.table_name,required.column_name as missing_column
from required
left join information_schema.columns actual
  on actual.table_schema='public'
 and actual.table_name=required.table_name
 and actual.column_name=required.column_name
where actual.column_name is null
order by required.table_name,required.column_name;

-- FINAL CHECK B — expected: one row, public=false, 10485760 bytes.
select id,name,public,file_size_limit,allowed_mime_types
from storage.buckets
where id='communication-attachments';

-- FINAL CHECK C — expected to include 2.6.0.
select version,applied_at
from public.pgc_schema_meta
order by applied_at desc
limit 8;
