const { sendEmail, cancelScheduledEmail, configured:emailConfigured, normaliseRecipients } = require('./email');
const store = require('./store');

const TIME_ZONE = 'Europe/London';
const MAX_PROVIDER_SCHEDULE_MS = 29 * 24 * 60 * 60 * 1000;
const MIN_PROVIDER_SCHEDULE_MS = 60 * 1000;

function clean(value,max=1000){return String(value ?? '').trim().replace(/\u0000/g,'').slice(0,max);}
function validDate(value){const v=clean(value,10);return /^\d{4}-\d{2}-\d{2}$/.test(v)?v:null;}
function validTime(value){const v=clean(value,5);return /^([01]\d|2[0-3]):[0-5]\d$/.test(v)?v:null;}
function validEmail(value){return normaliseRecipients(value)[0] || '';}

function offsetForLondon(date,time='12:00'){
  const probe=new Date(`${date}T${time}:00Z`);
  const parts=new Intl.DateTimeFormat('en-GB',{timeZone:TIME_ZONE,timeZoneName:'longOffset',hour:'2-digit'}).formatToParts(probe);
  const zone=parts.find(part=>part.type==='timeZoneName')?.value || 'GMT';
  const match=zone.match(/GMT([+-])(\d{2}):(\d{2})/);
  return match ? `${match[1]}${match[2]}:${match[3]}` : '+00:00';
}

function londonLocalToUtc(date,time){
  const d=validDate(date),t=validTime(time);
  if(!d || !t) throw new Error('INVALID_APPOINTMENT_DATETIME');
  const parsed=new Date(`${d}T${t}:00${offsetForLondon(d,t)}`);
  if(Number.isNaN(parsed.getTime())) throw new Error('INVALID_APPOINTMENT_DATETIME');
  return parsed;
}

function londonDateParts(instant){
  const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:TIME_ZONE,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(instant).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));
  return {date:`${parts.year}-${parts.month}-${parts.day}`,time:`${parts.hour}:${parts.minute}`};
}

function formatLondon(iso){
  return new Intl.DateTimeFormat('en-GB',{timeZone:TIME_ZONE,weekday:'long',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(iso));
}

function reminderMoments(start){
  const local=londonDateParts(start);
  return {
    advance_24h:new Date(start.getTime()-24*60*60*1000),
    morning_8am:londonLocalToUtc(local.date,'08:00'),
    thirty_minutes:new Date(start.getTime()-30*60*1000)
  };
}

function reminderLabel(type){
  if(type==='advance_24h') return 'Appointment reminder · 24 hours';
  if(type==='morning_8am') return 'Appointment reminder · today';
  return 'Appointment reminder · 30 minutes';
}

function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}

function reminderEmail(appointment,label,linkedName){
  const when=formatLondon(appointment.start_at);
  const linked=linkedName ? `\nFamily record: ${linkedName}` : '';
  const text=`${label}\n\nAppointment: ${appointment.title}\nType: ${appointment.appointment_type || 'Appointment'}${linked}\nWith: ${appointment.meeting_with || '—'}\nWhen: ${when}\nWhere: ${appointment.location || '—'}\n\nThis is an automatic reminder from Project Golden Child.`;
  const html=`<!doctype html><html><body style="margin:0;background:#f7f2e8;font-family:Arial,Helvetica,sans-serif;color:#2f251b"><div style="max-width:680px;margin:0 auto;padding:24px"><div style="background:#3a2818;color:#fff;padding:22px 24px;border-radius:16px 16px 0 0"><div style="font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:#edc35d">Project Golden Child</div><div style="font-size:25px;font-weight:800;margin-top:8px">${esc(label)}</div></div><div style="background:#fff;padding:24px;border:1px solid #e5dac8;border-top:4px solid #c39128"><p style="margin:0 0 18px">This is an automatic reminder for the following appointment.</p><table style="width:100%;border-collapse:collapse;font-size:14px"><tr><td style="padding:8px 0;color:#7b6e60;width:145px">Appointment</td><td style="padding:8px 0;font-weight:700">${esc(appointment.title)}</td></tr>${linkedName?`<tr><td style="padding:8px 0;color:#7b6e60">Family record</td><td style="padding:8px 0">${esc(linkedName)}</td></tr>`:''}<tr><td style="padding:8px 0;color:#7b6e60">With</td><td style="padding:8px 0">${esc(appointment.meeting_with || '—')}</td></tr><tr><td style="padding:8px 0;color:#7b6e60">When</td><td style="padding:8px 0">${esc(when)}</td></tr><tr><td style="padding:8px 0;color:#7b6e60">Where</td><td style="padding:8px 0">${esc(appointment.location || '—')}</td></tr></table></div><div style="font-size:12px;color:#786f66;padding:13px 4px">Automatically generated by the Project Golden Child appointments calendar.</div></div></body></html>`;
  return {text,html};
}

async function linkedName(appointment){
  if(appointment.hero_id){const h=await store.get('heroes',appointment.hero_id);return h?.preferred_name||h?.child_name||'';}
  if(appointment.referral_id){const r=await store.get('referrals',appointment.referral_id);return r?.child_name||'';}
  return '';
}

function reminderRecipients(appointment){
  const out=[];
  const admin=validEmail(process.env.APPOINTMENT_ADMIN_EMAIL || process.env.NOTIFICATION_EMAIL);
  if(appointment.reminder_admin !== false && admin) out.push({email:admin,name:'Project Golden Child admin',kind:'admin'});
  const family=validEmail(appointment.contact_email);
  if(appointment.reminder_family && family) out.push({email:family,name:appointment.meeting_with || 'Family contact',kind:'family'});
  const seen=new Set();
  return out.filter(r=>{if(seen.has(r.email))return false;seen.add(r.email);return true;});
}

async function cancelAppointmentReminders(appointmentId){
  const rows=await store.list('appointment_reminders',{filters:{appointment_id:appointmentId},order:'created_at.desc'});
  for(const row of rows){
    if(row.provider_message_id && row.status==='scheduled'){
      try{await cancelScheduledEmail(row.provider_message_id);}catch(err){console.error('Reminder cancellation failed',row.id,err.message);}
    }
    if(!['sent','cancelled'].includes(row.status)) await store.update('appointment_reminders',row.id,{status:'cancelled'});
  }
  return rows.length;
}

async function scheduleAppointmentReminders(appointment,now=new Date()){
  const start=new Date(appointment.start_at);
  if(Number.isNaN(start.getTime()) || start<=now || appointment.status==='cancelled') return {scheduled:0,deferred:0,skipped:0,failed:0,results:[]};
  const recipients=reminderRecipients(appointment);
  if(!recipients.length) return {scheduled:0,deferred:0,skipped:0,failed:0,results:[],warning:'No reminder recipient email is configured.'};
  const moments=reminderMoments(start);
  const enabled={advance_24h:appointment.reminder_24h!==false,morning_8am:appointment.reminder_morning!==false,thirty_minutes:appointment.reminder_30m!==false};
  const existing=await store.list('appointment_reminders',{filters:{appointment_id:appointment.id},order:'created_at.desc'});
  const name=await linkedName(appointment);
  const results=[];

  for(const [type,due] of Object.entries(moments)){
    if(!enabled[type]) continue;
    for(const recipient of recipients){
      const old=existing.find(r=>r.reminder_type===type && String(r.recipient_email||'').toLowerCase()===recipient.email);
      if(old && ['scheduled','sent'].includes(old.status)){results.push({type,email:recipient.email,status:'already_scheduled'});continue;}
      if(due>=start || due.getTime()-now.getTime()<MIN_PROVIDER_SCHEDULE_MS){results.push({type,email:recipient.email,status:'skipped_past'});continue;}

      const base={appointment_id:appointment.id,reminder_type:type,recipient_email:recipient.email,recipient_name:recipient.name,recipient_kind:recipient.kind,scheduled_for:due.toISOString(),status:'pending',error:null};
      const reminder=old ? await store.update('appointment_reminders',old.id,base) : await store.insert('appointment_reminders',base);

      if(due.getTime()-now.getTime()>MAX_PROVIDER_SCHEDULE_MS){
        await store.update('appointment_reminders',reminder.id,{status:'deferred'});
        results.push({type,email:recipient.email,status:'deferred',scheduledFor:due.toISOString()});
        continue;
      }
      if(!emailConfigured()){
        await store.update('appointment_reminders',reminder.id,{status:'failed',error:'Email delivery is not configured.'});
        results.push({type,email:recipient.email,status:'failed',error:'Email delivery is not configured.'});
        continue;
      }
      try{
        const content=reminderEmail(appointment,reminderLabel(type),name);
        const sent=await sendEmail({to:recipient.email,subject:`${reminderLabel(type)}: ${appointment.title}`,text:content.text,html:content.html,scheduledAt:due.toISOString(),replyTo:process.env.REPLY_TO_EMAIL || process.env.NOTIFICATION_EMAIL,tags:[{name:'category',value:'pgc_appointment'}]});
        await store.update('appointment_reminders',reminder.id,{status:'scheduled',provider_message_id:sent.id||null,error:null});
        results.push({type,email:recipient.email,status:'scheduled',scheduledFor:due.toISOString(),providerMessageId:sent.id||null});
      }catch(err){
        await store.update('appointment_reminders',reminder.id,{status:'failed',error:String(err.message||err).slice(0,1000)});
        results.push({type,email:recipient.email,status:'failed',error:err.message||'Email scheduling failed'});
      }
    }
  }
  return {scheduled:results.filter(r=>r.status==='scheduled').length,deferred:results.filter(r=>r.status==='deferred').length,skipped:results.filter(r=>String(r.status).startsWith('skipped')||r.status==='already_scheduled').length,failed:results.filter(r=>r.status==='failed').length,results};
}

module.exports={TIME_ZONE,clean,validDate,validTime,validEmail,londonLocalToUtc,formatLondon,reminderMoments,scheduleAppointmentReminders,cancelAppointmentReminders,reminderRecipients};
