const {json,readBody,cleanText}=require('../lib/http'); const {requireAdmin}=require('../lib/security'); const store=require('../lib/store'); const {audit}=require('../lib/audit');
module.exports=async function(req,res){ const user=requireAdmin(req,res); if(!user) return; try{
 if(req.method==='GET'){const items=await store.list('heroes',{order:'created_at.desc'}); const actions=await store.list('hero_actions',{order:'created_at.desc'}); return json(res,200,{items:items.map(h=>({...h,actions:actions.filter(a=>a.hero_id===h.id)}))});}
 if(req.method==='POST'){const b=await readBody(req); if(b.action==='add-action'){const hero=await store.get('heroes',cleanText(b.hero_id,80)); if(!hero) return json(res,404,{message:'Hero not found.'}); const item=await store.insert('hero_actions',{hero_id:hero.id,action_type:cleanText(b.action_type||'Recognition',100),title:cleanText(b.title,240),due_date:cleanText(b.due_date,30)||null,status:'open',notes:cleanText(b.notes,2000),value_gbp:Number(b.value_gbp||0)}); await audit(user,'create','hero_action',item.id,{hero_id:hero.id}); return json(res,201,{item});}
 if(b.action==='complete-action'){const item=await store.update('hero_actions',cleanText(b.id,80),{status:'completed',completed_at:new Date().toISOString()}); await audit(user,'complete','hero_action',b.id); return json(res,200,{item});}
 if(b.action==='update-hero'){const id=cleanText(b.id,80); const patch={}; for(const k of ['status','admin_notes','primary_contact_name','primary_contact_email','primary_contact_phone']) if(b[k]!==undefined) patch[k]=cleanText(b[k],k==='admin_notes'?4000:180); const item=await store.update('heroes',id,patch); await audit(user,'update','hero',id,patch); return json(res,200,{item});}
 return json(res,400,{message:'Unknown action.'}); }
 return json(res,405,{message:'Method not allowed.'});
 }catch(err){console.error(err); return json(res,503,{message:'Harper’s Heroes data is unavailable.'});} };
